// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB9BKkfuWHmgmMijGQxe9rwT7zAyx-Awk',
    appId: '1:733789590237:web:b1be6904fea8bafe190134',
    messagingSenderId: '733789590237',
    projectId: 'iot-project-5d401',
    authDomain: 'iot-project-5d401.firebaseapp.com',
    databaseURL: 'https://iot-project-5d401-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-5d401.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2cCGZR4tIijtdnWY18MJ2uq8XmaNroo',
    appId: '1:733789590237:android:6acd4cc1383f29e6190134',
    messagingSenderId: '733789590237',
    projectId: 'iot-project-5d401',
    databaseURL: 'https://iot-project-5d401-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-5d401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzDeIAmwPrhiEAYSo1WKY8XGeJZ_4PKww',
    appId: '1:733789590237:ios:dcb03340aaaf57f5190134',
    messagingSenderId: '733789590237',
    projectId: 'iot-project-5d401',
    databaseURL: 'https://iot-project-5d401-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-5d401.firebasestorage.app',
    iosBundleId: 'com.example.smartIrrigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzDeIAmwPrhiEAYSo1WKY8XGeJZ_4PKww',
    appId: '1:733789590237:ios:dcb03340aaaf57f5190134',
    messagingSenderId: '733789590237',
    projectId: 'iot-project-5d401',
    databaseURL: 'https://iot-project-5d401-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-5d401.firebasestorage.app',
    iosBundleId: 'com.example.smartIrrigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB9BKkfuWHmgmMijGQxe9rwT7zAyx-Awk',
    appId: '1:733789590237:web:96c55e9995622593190134',
    messagingSenderId: '733789590237',
    projectId: 'iot-project-5d401',
    authDomain: 'iot-project-5d401.firebaseapp.com',
    databaseURL: 'https://iot-project-5d401-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-5d401.firebasestorage.app',
  );
}
